### ISSUE TITLE
Alignment Broken with multiple DW Menus

### ISSUE THREAD

**Issue by TheZachh** [Progi1984/dokuwiki-dwmenu#10]
Using multiple "align=center" <dwmenu> tags  on one page, and being sure each one is closed with </dwmenu> results in a broken/cascading structure as opposed to properly seperated and centered menus. 

 I've tried to fix it but everything makes it worse. Aligning everything to left and right works but center apparently breaks the rest of the menu entities due to their being no differentiation between the entities as the very top menu block seems to spill its parameters of alignment over to the rest of what are supposed to be seperate menu blocks.   

![screenshot 2016-05-08 04 40 08](https://cloud.githubusercontent.com/assets/19249281/15097100/f553f034-14d6-11e6-81b2-66e85efa06f7.png)
![screenshot 2016-05-08 04 38 41](https://cloud.githubusercontent.com/assets/19249281/15097095/cfba1e52-14d6-11e6-81c1-4db72c462d3b.png)

**Comment by Progi1984** [comment]
@TheZachh Normally, it's fixed with the PR #11.
