### ISSUE TITLE
Invalid number of columns

### ISSUE THREAD

**Issue by MichielvanErven** [Progi1984/dokuwiki-dwmenu#2]
I'm trying to have 3 columns. When I specify col="3" The number of columns remain at 2. However, when I say col="4" Then three columns appear.  Using "Adora Belle"

- Edit - Same applies when having 4 or 5 columns. I have to add 1 column to have the correct number of columns.

**Comment by bluewindthings** [comment]
I investigated on this and found the reason if I'm correct: in style.css the percentage of space reserved to columns is a bit optimistic, given the extra margin per column granted in dwmenu_item class (padding). I'm using now this for 3 and 4 columns and it works:

    .dwmenu_item.column3{width:32%}
    .dwmenu_item.column4{width:24%}

**Comment by Progi1984** [comment]
Fixed in master branch
